### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by RuohuaTang** [cckuailong/SuperAdapters#4]
Hi, thanks for your SuperAdapters. However, I have tried it on my PC with a 4070ti and 32GB memory using eaxample.json as the dataset, I got:

The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  1.35it/s]
trainable params: 17,891,328 || all params: 7,739,215,872 || trainable%: 0.23117752878207867
Downloading data files: 100%|███████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 997.69it/s]
Extracting data files: 100%|█████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.56it/s]
Generating train split: 3 examples [00:00, 128.04 examples/s]
DatasetDict({
    train: Dataset({
        features: ['instruction', 'input', 'output'],
        num_rows: 3
    })
})
Map: 100%|████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 79.54 examples/s]
Map: 100%|████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 79.70 examples/s]
Traceback (most recent call last):
  File "E:\Desktop\LLM\SuperAdapters_master\SuperAdapters_master\finetune.py", line 140, in <module>
    llm.finetune(args.fromdb, args.db_iteration)
  File "E:\Desktop\LLM\SuperAdapters_master\SuperAdapters_master\core\seq2seq\qwen.py", line 232, in finetune
    trainer = transformers.Trainer(
  File "E:\miniconda\envs\llmenv\lib\site-packages\transformers\trainer.py", line 499, in __init__
    self._move_model_to_device(model, args.device)
  File "E:\miniconda\envs\llmenv\lib\site-packages\transformers\trainer.py", line 741, in _move_model_to_device
    model = model.to(device)
  File "E:\miniconda\envs\llmenv\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "E:\miniconda\envs\llmenv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "E:\miniconda\envs\llmenv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "E:\miniconda\envs\llmenv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "E:\miniconda\envs\llmenv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "E:\miniconda\envs\llmenv\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

**Comment by RuohuaTang** [comment]
I got this during fine-tuning Qwen-7B. I'm not sure if it is out of my GPU memory, 12GB.

**Comment by cckuailong** [comment]
Please try to add "--load_8bit" parameter in your command.

**Comment by RuohuaTang** [comment]
> 

Many thanks! It works now !!
